# Generated by Django 4.2 on 2023-06-10 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 15, 19, 16, 950019)),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 6, 10, 15, 19, 16, 951016))),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_menus.menu')),
            ],
        ),
    ]
