# Generated by Django 4.2 on 2023-06-10 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menus', '0002_alter_menu_menu_created_at_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 15, 26, 0, 791184)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 15, 26, 0, 791184)),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='order',
            table='restro_Order',
        ),
    ]
