# Generated by Django 4.2 on 2023-06-25 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menus', '0003_alter_order_options_alter_menu_menu_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 15, 35, 21, 264222)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 15, 35, 21, 265219)),
        ),
    ]
